import { FiArrowRight, FiArrowUpRight } from 'react-icons/fi';
export default function Home() {
  return (
    <main>
      <section className="hero"><p className="eyebrow">AI-assisted UK tax research</p><h1>Better answers.<br /><span>Closer to the source.</span></h1><p className="lede">Move from a tax question to a cited, reviewable answer. GAIN Tax helps professionals spend less time searching and more time applying their judgement.</p><div className="actions"><a className="button" href="/pricing">Explore plans <b><FiArrowUpRight /></b></a><a className="quiet-link" href="/benchmark">See the benchmark <span><FiArrowRight /></span></a></div><p className="caption">14-day trial · no card required</p></section>
 <section className="wide-image"><img src="/assets/tax-adviser.png" width="1536" height="1024" fetchPriority="high" alt="A tax adviser reviewing papers beside an open reference book" /><div className="image-note"><span>RESEARCH, IN CONTEXT</span><span>UK tax sources · cited answers</span></div></section>
 <section className="proof-strip"><div><b>250</b><span>benchmark questions</span></div><div><b>21</b><span>UK tax domains</span></div><div><b>93.2%</b><span>fully correct responses</span></div><a href="/benchmark">See how it was measured <span><FiArrowRight /></span></a></section>
 <section className="section intro-grid"><div><p className="eyebrow">A clearer way to research</p><h2>Start with the question.<br />Stay close to the evidence.</h2></div><p className="section-copy">GAIN Tax brings relevant legislation, HMRC manuals and guidance into a structured answer. Follow the citations, check the material, then apply your own professional judgement.</p></section>
 <section className="feature-band"><div className="feature-text"><p className="eyebrow">01 / FIND THE RULE</p><h2>From question<br />to relevant source.</h2><p>Explore UK tax questions with answers linked back to source material, so you can verify the point that matters.</p><a className="quiet-link" href="/product">Explore the product <span><FiArrowRight /></span></a></div><div className="research-preview"><div className="preview-head"><span>GAIN TAX · RESEARCH</span><span>ANSWER WITH SOURCES</span></div><h3>How does the annual investment allowance apply?</h3><p>The annual investment allowance provides 100% relief on qualifying plant and machinery expenditure, subject to the current limit and statutory conditions.</p><div className="source-row"><b>01</b><span>Capital Allowances Act 2001 · s.38A</span><i>Open source <FiArrowUpRight /></i></div><div className="source-row"><b>02</b><span>HMRC Capital Allowances Manual · CA23080</span><i>Open source <FiArrowUpRight /></i></div><small>Illustrative example · check the current rules and facts</small></div></section>
 <section className="image-story"><div className="image-story-media"><img src="/assets/research-desk.png" width="1536" height="1024" loading="lazy" decoding="async" alt="Open legislation and research papers on a desk" /><span>THE SOURCE STAYS IN VIEW</span></div><div className="image-story-copy"><p className="eyebrow">RESEARCH, THEN REVIEW</p><h2>Keep the source close to the decision.</h2><p>Read the answer in context, follow its references and decide what the facts mean for your client.</p><a className="quiet-link" href="/sources">How GAIN Tax uses sources <span><FiArrowRight /></span></a></div></section>
 <section className="section split"><div><p className="eyebrow">02 / REVIEW WITH CONTEXT</p><h2>Keep the facts<br />in the frame.</h2><p className="section-copy">Client context and document analysis help turn a broad research question into work that reflects the matter in front of you.</p><a className="quiet-link" href="/product">See product capabilities <span><FiArrowRight /></span></a></div><div className="soft-panel"><span className="panel-label">CLIENT CONTEXT</span><h3>Property portfolio · individual client</h3><div className="context-line"><span>Question</span><b>Relief on mixed-use expenditure</b></div><div className="context-line"><span>Documents</span><b>3 files in workspace</b></div><div className="context-line"><span>Research date</span><b>Current position</b></div><div className="blue-rule"></div><p>Relevant facts stay close to the question while you review the sources and refine your analysis.</p></div></section>
 <section className="quote-section"><p className="eyebrow">IN PRACTICE · LIONDARIS & CO</p><blockquote>“GAIN Tax is going to be as accurate as possible because it’s picking legislation up. It’s not making it up.”</blockquote><div className="quote-by">Christos Liondaris <span>Managing Partner, Liondaris & Co</span></div><a className="quiet-link" href="/case-study">Read the customer story <span><FiArrowRight /></span></a></section>
 <section className="cta-section"><p className="eyebrow">MAKE ROOM FOR THE WORK THAT NEEDS YOU</p><h2>Bring your next tax question.</h2><p>Try GAIN Tax for 14 days. No credit card required.</p><a className="button" href="/pricing">Find your plan <b><FiArrowUpRight /></b></a></section>
    </main>
  );
}
